// Fictional seed data for the demo: an HV engineering / EPC contractor.
// Every person, supplier, project and number here is made up. Nothing is
// drawn from any client.

import type { Brief, Person, Project, PurchaseOrder, Supplier, Workstream } from './types'

export const PEOPLE: Person[] = [
  { id: 'helen', name: 'Helen Marsh', role: 'Head of Finance - change lead' },
  { id: 'sarah', name: 'Sarah Whitfield', role: 'Procurement Manager' },
  { id: 'tom', name: 'Tom Aldridge', role: 'Project Manager' },
  { id: 'kate', name: 'Kate Donnelly', role: 'Commercial Manager' },
  { id: 'marcus', name: 'Marcus Reid', role: 'Site Manager' },
  { id: 'ben', name: 'Ben Carmichael', role: 'IT Operations Lead' },
  { id: 'owen', name: 'Owen Reilly', role: 'Engineering Manager' },
  { id: 'liam', name: 'Liam Pryor', role: 'Commissioning Manager' },
  { id: 'ramsay', name: 'Ramsay Hatfield', role: 'Builder - CoreSentia' },
]

// Per-client configuration. This set is for a high-voltage grid-connection
// EPC contractor. The next client gets a different five lines.
export const WORKSTREAMS: Workstream[] = [
  { id: 'foundations', name: 'Foundations', goal: 'Identity, the project record and the plumbing everything else hangs off.', owner: 'Ben Carmichael', tone: 'blue' },
  { id: 'pipeline', name: 'Project pipeline', goal: 'One project record from development to handover, with a gate at every stage.', owner: 'Tom Aldridge', tone: 'purple' },
  { id: 'finance', name: 'Finance & procurement', goal: 'Committed and claimed cost visible the day it happens, posted to the ERP without re-keying.', owner: 'Helen Marsh', tone: 'green' },
  { id: 'site', name: 'Site & HSEQ', goal: 'Site records, inductions and commissioning checks from a phone, audit-ready.', owner: 'Marcus Reid', tone: 'orange' },
  { id: 'reporting', name: 'Reporting', goal: 'Dashboards and the board pack from live data, every number traceable.', owner: 'Helen Marsh', tone: 'teal' },
]

// Departments are tags on a brief, not a level of hierarchy.
export const DEPARTMENTS = ['Engineering', 'Procurement', 'Construction', 'Commissioning', 'Finance', 'Site', 'HSEQ', 'IT']

// Who the demo can act as. The change log and audit trail record this name.
export const ACTORS = ['ramsay', 'helen', 'tom', 'sarah']
export const DEFAULT_ACTOR = 'ramsay'

export const SUPPLIERS: Supplier[] = [
  { id: 's1', name: 'Siebert Switchgear Pty Ltd', category: 'HV switchgear' },
  { id: 's2', name: 'Redgum Crane & Rigging', category: 'Crane hire' },
  { id: 's3', name: 'Hollis Electrical Wholesale', category: 'Cable and consumables' },
  { id: 's4', name: 'Brightwater Civil Contractors', category: 'Civil works' },
  { id: 's5', name: 'Nordvik Transformer Services', category: 'Transformer testing' },
]

export const PROJECTS: Project[] = [
  { id: 'p1', code: 'P-2041', name: 'Marlow Creek BESS', manager: 'Tom Aldridge' },
  { id: 'p2', code: 'P-2038', name: 'Wandera Plains Solar Farm', manager: 'Tom Aldridge' },
  { id: 'p3', code: 'P-2045', name: 'Kingsholme 132kV Substation', manager: 'Tom Aldridge' },
  { id: 'p4', code: 'P-2050', name: 'Brennan Range Wind Connection', manager: 'Tom Aldridge' },
]

// ---------- Tracker briefs ----------

type LogSeed = [at: string, who: string, action: string]
const log = (entries: LogSeed[]) =>
  entries.map(([at, who, action], i) => ({ id: `l${i}-${at}`, at, who, action }))

type FbSeed = [at: string, author: string, text: string, status: 'open' | 'addressed']
const fb = (entries: FbSeed[]) =>
  entries.map(([at, author, text, status], i) => ({ id: `f${i}-${at}`, at, author, text, status }))

export const BRIEFS: Brief[] = [
  // ---------- Foundations ----------
  {
    id: 'f01',
    title: 'Entra ID sign-in and roles',
    module: 'Identity',
    workstream: 'foundations',
    department: 'IT',
    owner: 'Ben Carmichael',
    priority: 'P1',
    workType: 'module',
    days: 4,
    signOff: 'signed off',
    signOffBy: ['Ben Carmichael'],
    stage: 'Done',
    outcome: 'Everyone signs in with the account they already have. Roles come from the directory groups IT already manages. No new passwords.',
    currentState: 'Spreadsheets and email have no sign-in at all. The ERP has its own accounts, managed by hand.',
    lockDate: '2026-06-11',
    targetDate: '2026-06-19',
    previewUrl: '',
    readmeUrl: '#readme-identity',
    internalOwner: 'Ben Carmichael',
    feedback: fb([['2026-06-17T10:20:00+10:00', 'Ben Carmichael', 'Group to role mapping should be a table IT can edit, not code.', 'addressed']]),
    changeLog: log([
      ['2026-06-09T09:00:00+10:00', 'Ben Carmichael', 'Request raised. Entered Mapping.'],
      ['2026-06-10T10:00:00+10:00', 'Helen Marsh', 'Ranked P1. First thing built.'],
      ['2026-06-11T14:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-06-12T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-06-15T17:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-06-17T09:00:00+10:00', 'Ben Carmichael', 'Testing started. Moved from Preview to Testing.'],
      ['2026-06-18T16:00:00+10:00', 'Ramsay Hatfield', 'Promoted to production. Moved from Testing to Production.'],
      ['2026-06-19T11:00:00+10:00', 'Ben Carmichael', 'Signed off. Moved from Production to Done.'],
    ]),
    attachments: [],
  },
  {
    id: 'b01',
    title: 'Build the tracker',
    module: 'Tracker',
    workstream: 'foundations',
    department: 'IT',
    owner: 'Helen Marsh',
    priority: 'P1',
    workType: 'module',
    days: 3,
    signOff: 'signed off',
    signOffBy: ['Helen Marsh'],
    stage: 'Done',
    outcome: 'One place every request enters, ranked by the change lead. Nothing reaches the builder by direct message.',
    currentState: 'Requests arrived by email, Teams and hallway. No shared list. Priority was decided by whoever asked last.',
    lockDate: '2026-06-17',
    targetDate: '2026-06-24',
    previewUrl: '/demo/tracker',
    readmeUrl: '#readme-tracker',
    internalOwner: 'Helen Marsh',
    feedback: fb([['2026-06-22T09:40:00+10:00', 'Helen Marsh', 'Cards need the days estimate on the front, not in the detail.', 'addressed']]),
    changeLog: log([
      ['2026-06-15T08:30:00+10:00', 'Helen Marsh', 'Request raised. Entered Mapping.'],
      ['2026-06-16T10:05:00+10:00', 'Helen Marsh', 'Ranked P1. Moved from Mapping to Briefed in.'],
      ['2026-06-17T14:20:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-06-18T08:10:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-06-19T16:45:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-06-22T09:35:00+10:00', 'Helen Marsh', 'Clicked through against the brief. Moved from Preview to Testing.'],
      ['2026-06-23T11:00:00+10:00', 'Ramsay Hatfield', 'Feedback addressed. Promoted to production. Moved from Testing to Production.'],
      ['2026-06-24T09:15:00+10:00', 'Ramsay Hatfield', 'README written. Internal owner named: Helen Marsh.'],
      ['2026-06-24T15:30:00+10:00', 'Helen Marsh', 'Signed off. Moved from Production to Done.'],
    ]),
    attachments: [],
  },
  {
    id: 'b02',
    title: 'Project record - core',
    module: 'Project Record',
    workstream: 'foundations',
    department: 'Engineering',
    owner: 'Tom Aldridge',
    priority: 'P1',
    workType: 'module',
    days: 12,
    signOff: 'signed off',
    signOffBy: ['Tom Aldridge', 'Kate Donnelly'],
    stage: 'Done',
    outcome: 'Every project has one record: code, client, connection point, voltage, contract value, key dates, project manager. Everything else hangs off it.',
    currentState: 'The project list lived in a spreadsheet on SharePoint with three copies in circulation.',
    lockDate: '2026-06-26',
    targetDate: '2026-07-24',
    previewUrl: 'https://platform-git-project-record.vercel.app',
    readmeUrl: '#readme-project-record',
    internalOwner: 'Tom Aldridge',
    feedback: fb([
      ['2026-07-14T10:20:00+10:00', 'Kate Donnelly', 'Contract value should be ex GST with the inc GST figure shown beside it.', 'addressed'],
      ['2026-07-15T08:50:00+10:00', 'Tom Aldridge', 'Practical completion date is a target until certified. Show which.', 'addressed'],
    ]),
    changeLog: log([
      ['2026-06-18T09:00:00+10:00', 'Tom Aldridge', 'Request raised. Entered Mapping.'],
      ['2026-06-19T11:30:00+10:00', 'Helen Marsh', 'Ranked P1. The spine everything hangs off.'],
      ['2026-06-24T13:00:00+10:00', 'Tom Aldridge', 'Current-state process mapped. Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-06-26T09:10:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-06-29T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-07-09T17:10:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-07-13T09:00:00+10:00', 'Tom Aldridge', 'Testing started. Moved from Preview to Testing.'],
      ['2026-07-17T15:40:00+10:00', 'Ramsay Hatfield', 'Iteration round one complete. Promoted to production. Moved from Testing to Production.'],
      ['2026-07-21T10:00:00+10:00', 'Ramsay Hatfield', 'README written. Tests on the record to purchase orders path. Internal owner named: Tom Aldridge.'],
      ['2026-07-24T14:05:00+10:00', 'Tom Aldridge', 'Signed off with Kate Donnelly. Moved from Production to Done.'],
    ]),
    attachments: [],
  },
  {
    id: 'f04',
    title: 'Audit log on every record',
    module: 'Audit',
    workstream: 'foundations',
    department: 'IT',
    owner: 'Ben Carmichael',
    priority: 'P1',
    workType: 'module',
    days: 3,
    signOff: 'awaiting',
    signOffBy: ['Ben Carmichael', 'Helen Marsh'],
    stage: 'Production',
    outcome: 'Who changed what, when, on every record in the platform. Read-only, exportable, kept for seven years.',
    currentState: 'Change history lives in email threads and file versions. Reconstructing a decision takes an afternoon.',
    lockDate: '2026-08-05',
    targetDate: '2026-09-19',
    previewUrl: '',
    readmeUrl: '#readme-audit',
    internalOwner: 'Ben Carmichael',
    feedback: fb([['2026-08-20T11:00:00+10:00', 'Helen Marsh', 'Export needs to be filterable by project and date range for the auditors.', 'addressed']]),
    changeLog: log([
      ['2026-07-28T09:00:00+10:00', 'Ben Carmichael', 'Request raised. Entered Mapping.'],
      ['2026-07-29T10:00:00+10:00', 'Helen Marsh', 'Ranked P1. Needed before finance modules go live.'],
      ['2026-08-04T14:00:00+10:00', 'Ben Carmichael', 'Brief submitted. Moved from Mapping to Briefed in.'],
      ['2026-08-05T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-08-11T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-08-15T17:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-08-19T09:00:00+10:00', 'Ben Carmichael', 'Testing started. Moved from Preview to Testing.'],
      ['2026-08-25T16:00:00+10:00', 'Ramsay Hatfield', 'Promoted to production. Moved from Testing to Production.'],
      ['2026-09-08T10:00:00+10:00', 'Ramsay Hatfield', 'README written. Awaiting sign-off from Ben Carmichael and Helen Marsh.'],
    ]),
    attachments: [],
  },
  {
    id: 'f05',
    title: 'ERP connection - service account and test company',
    module: 'ERP Sync',
    workstream: 'foundations',
    department: 'IT',
    owner: 'Ben Carmichael',
    priority: 'P1',
    workType: 'integration',
    days: 3,
    signOff: 'not started',
    signOffBy: ['Ben Carmichael'],
    stage: 'Mapping',
    outcome: 'A service account for the platform in the ERP, scoped to what it needs, and a test company to build against. Nothing touches live books until finance says so.',
    currentState: 'Integration work has been quoted by outside consultants. No API access exists yet.',
    lockDate: null,
    targetDate: '2026-10-02',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Ben Carmichael',
    feedback: [],
    changeLog: log([
      ['2026-09-01T09:00:00+10:00', 'Ben Carmichael', 'Request raised. Entered Mapping.'],
      ['2026-09-01T11:00:00+10:00', 'Helen Marsh', 'Ranked P1. Filed as integration. Everything in Finance & procurement depends on it.'],
      ['2026-09-09T11:00:00+10:00', 'Ben Carmichael', 'API access requested from the ERP vendor. Waiting on the account.'],
    ]),
    attachments: [],
  },

  // ---------- Project pipeline ----------
  {
    id: 'p01',
    title: 'Stage model - development to handover',
    module: 'Project Record',
    workstream: 'pipeline',
    department: 'Engineering',
    owner: 'Tom Aldridge',
    priority: 'P1',
    workType: 'module',
    days: 10,
    signOff: 'awaiting',
    signOffBy: ['Tom Aldridge', 'Owen Reilly', 'Liam Pryor'],
    stage: 'Production',
    outcome: 'Every project moves through the same stages: development, grid connection studies, engineering design, procurement, construction, commissioning and testing, handover. One stage at a time. Each stage has an owner.',
    currentState: 'Stage is whatever the project manager says it is in the Monday meeting. No two projects use the same words.',
    lockDate: '2026-07-31',
    targetDate: '2026-09-26',
    previewUrl: 'https://platform-git-stages.vercel.app',
    readmeUrl: '#readme-stages',
    internalOwner: 'Tom Aldridge',
    feedback: fb([
      ['2026-08-26T10:00:00+10:00', 'Owen Reilly', 'Grid connection studies can run in parallel with early design. The model needs an overlap, not a hard gate.', 'addressed'],
      ['2026-09-02T14:30:00+10:00', 'Liam Pryor', 'Commissioning has sub-stages: pre-commissioning, energisation, hold point testing. One stage is too coarse.', 'open'],
    ]),
    changeLog: log([
      ['2026-07-20T09:00:00+10:00', 'Tom Aldridge', 'Request raised. Entered Mapping.'],
      ['2026-07-21T10:00:00+10:00', 'Helen Marsh', 'Ranked P1.'],
      ['2026-07-29T15:00:00+10:00', 'Tom Aldridge', 'Stages mapped with engineering and commissioning. Brief submitted. Moved from Mapping to Briefed in.'],
      ['2026-07-31T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-08-04T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-08-19T17:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-08-25T09:00:00+10:00', 'Tom Aldridge', 'Testing started with engineering and commissioning. Moved from Preview to Testing.'],
      ['2026-09-05T16:00:00+10:00', 'Ramsay Hatfield', 'Promoted to production. Moved from Testing to Production.'],
      ['2026-09-10T10:00:00+10:00', 'Ramsay Hatfield', 'README written. Commissioning sub-stages raised as a new request.'],
    ]),
    attachments: [],
  },
  {
    id: 'p02',
    title: 'Stage gates and sign-offs',
    module: 'Project Record',
    workstream: 'pipeline',
    department: 'Engineering',
    owner: 'Tom Aldridge',
    priority: 'P1',
    workType: 'module',
    days: 5,
    signOff: 'not started',
    signOffBy: ['Tom Aldridge', 'Helen Marsh'],
    stage: 'Testing',
    outcome: 'A project cannot leave a stage until the gate is met: named sign-offs, required documents, no open hold points. The gate is visible on the record.',
    currentState: 'Gates are a checklist in a shared document that is sometimes updated after the fact.',
    lockDate: '2026-08-22',
    targetDate: '2026-09-30',
    previewUrl: 'https://platform-git-stage-gates.vercel.app',
    readmeUrl: '',
    internalOwner: 'Tom Aldridge',
    feedback: fb([['2026-09-11T09:30:00+10:00', 'Tom Aldridge', 'Allow an override with a reason, logged, for when the client forces a start.', 'open']]),
    changeLog: log([
      ['2026-08-11T09:00:00+10:00', 'Tom Aldridge', 'Request raised. Entered Mapping.'],
      ['2026-08-12T10:00:00+10:00', 'Helen Marsh', 'Ranked P1.'],
      ['2026-08-20T15:00:00+10:00', 'Tom Aldridge', 'Brief submitted with gate definitions attached. Moved from Mapping to Briefed in.'],
      ['2026-08-22T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-09-01T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-09-08T17:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-09-10T09:00:00+10:00', 'Tom Aldridge', 'Testing started. Moved from Preview to Testing.'],
    ]),
    attachments: [],
  },
  {
    id: 'p03',
    title: 'Engineering design register',
    module: 'Engineering',
    workstream: 'pipeline',
    department: 'Engineering',
    owner: 'Owen Reilly',
    priority: 'P2',
    workType: 'module',
    days: 7,
    signOff: 'not started',
    signOffBy: ['Owen Reilly'],
    stage: 'Build',
    outcome: 'Every drawing and study against the project with revision, status and who issued it. Issued for construction is a state, not a file name.',
    currentState: 'Drawings live in a folder tree. The current revision is whichever one was emailed last.',
    lockDate: '2026-09-03',
    targetDate: '2026-10-09',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Owen Reilly',
    feedback: [],
    changeLog: log([
      ['2026-08-18T09:00:00+10:00', 'Owen Reilly', 'Request raised. Entered Mapping.'],
      ['2026-08-19T10:00:00+10:00', 'Helen Marsh', 'Ranked P2.'],
      ['2026-09-01T14:00:00+10:00', 'Owen Reilly', 'Brief submitted. Moved from Mapping to Briefed in.'],
      ['2026-09-03T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-09-09T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
    ]),
    attachments: [],
  },
  {
    id: 'p04',
    title: 'Commissioning and testing records',
    module: 'Commissioning',
    workstream: 'pipeline',
    department: 'Commissioning',
    owner: 'Liam Pryor',
    priority: 'P1',
    workType: 'module',
    days: 8,
    signOff: 'not started',
    signOffBy: ['Liam Pryor'],
    stage: 'Locked',
    outcome: 'Test sheets, hold points and energisation approvals recorded against the project as they happen, on site, with the witness named.',
    currentState: 'Paper test sheets scanned at the end of the job. Hold point releases by phone.',
    lockDate: '2026-09-10',
    targetDate: '2026-10-23',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Liam Pryor',
    feedback: [],
    changeLog: log([
      ['2026-08-25T09:00:00+10:00', 'Liam Pryor', 'Request raised. Entered Mapping.'],
      ['2026-08-26T10:00:00+10:00', 'Helen Marsh', 'Ranked P1. Client asks for these records at handover.'],
      ['2026-09-08T15:00:00+10:00', 'Liam Pryor', 'Brief submitted with the test sheet set attached. Moved from Mapping to Briefed in.'],
      ['2026-09-10T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set. Build starts after the design register.'],
    ]),
    attachments: [],
  },
  {
    id: 'p05',
    title: 'Construction progress - percent complete by area',
    module: 'Construction',
    workstream: 'pipeline',
    department: 'Construction',
    owner: 'Marcus Reid',
    priority: 'P2',
    workType: 'module',
    days: 6,
    signOff: 'not started',
    signOffBy: ['Marcus Reid', 'Tom Aldridge'],
    stage: 'Briefed in',
    outcome: 'Site reports percent complete by work area each week. The project record shows it against plan. Claims use it.',
    currentState: 'Progress is a number the site manager gives the project manager on Friday, from memory.',
    lockDate: null,
    targetDate: '2026-10-30',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: [],
    changeLog: log([
      ['2026-09-02T09:00:00+10:00', 'Marcus Reid', 'Request raised. Entered Mapping.'],
      ['2026-09-03T10:00:00+10:00', 'Helen Marsh', 'Ranked P2.'],
      ['2026-09-11T16:00:00+10:00', 'Marcus Reid', 'Brief submitted with the area breakdown attached. Moved from Mapping to Briefed in.'],
    ]),
    attachments: [],
  },
  {
    id: 'p06',
    title: 'Grid connection studies - milestone tracking',
    module: 'Engineering',
    workstream: 'pipeline',
    department: 'Engineering',
    owner: 'Owen Reilly',
    priority: 'P2',
    workType: 'module',
    days: 5,
    signOff: 'not started',
    signOffBy: ['Owen Reilly'],
    stage: 'Mapping',
    outcome: 'Study milestones and network operator submissions tracked per project with due dates and status. The long lead item made visible.',
    currentState: 'Tracked in the engineering manager head and a personal spreadsheet.',
    lockDate: null,
    targetDate: '2026-11-13',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Owen Reilly',
    feedback: [],
    changeLog: log([
      ['2026-09-09T09:00:00+10:00', 'Owen Reilly', 'Request raised. Entered Mapping.'],
      ['2026-09-10T10:00:00+10:00', 'Helen Marsh', 'Ranked P2. After the design register.'],
    ]),
    attachments: [],
  },

  // ---------- Finance & procurement ----------
  {
    id: 'b03',
    title: 'Purchase orders - raise and approve',
    module: 'Purchase Orders',
    workstream: 'finance',
    department: 'Procurement',
    owner: 'Sarah Whitfield',
    priority: 'P1',
    workType: 'module',
    days: 10,
    signOff: 'awaiting',
    signOffBy: ['Sarah Whitfield', 'Helen Marsh'],
    stage: 'Production',
    outcome: 'Raise a PO against a project, route it by value, approve it on a phone, post it to the ERP. Audit trail on every step.',
    currentState: 'PO template in Excel, emailed for signature, re-keyed into the ERP by accounts. About 40 a week. No view of committed cost until the invoice lands.',
    lockDate: '2026-07-28',
    targetDate: '2026-09-18',
    previewUrl: '/demo/purchase-orders',
    readmeUrl: '#readme-purchase-orders',
    internalOwner: 'Sarah Whitfield',
    feedback: fb([
      ['2026-08-17T11:15:00+10:00', 'Sarah Whitfield', 'Approver names should show the role as well as the name.', 'addressed'],
      ['2026-08-17T14:00:00+10:00', 'Tom Aldridge', 'Put the routing rule on the raise screen. Nobody reads help pages.', 'addressed'],
      ['2026-08-18T09:30:00+10:00', 'Helen Marsh', 'The threshold is ex GST. Say so on screen.', 'addressed'],
      ['2026-09-04T16:20:00+10:00', 'Sarah Whitfield', 'Supplier list needs an inactive flag so retired suppliers drop out of the select.', 'open'],
    ]),
    changeLog: log([
      ['2026-07-06T09:20:00+10:00', 'Sarah Whitfield', 'Request raised. Entered Mapping.'],
      ['2026-07-07T08:45:00+10:00', 'Helen Marsh', 'Ranked P1. First module after the project record.'],
      ['2026-07-13T10:00:00+10:00', 'Ramsay Hatfield', 'Mapping update one: architecture and data model returned.'],
      ['2026-07-20T10:00:00+10:00', 'Ramsay Hatfield', 'Mapping update two: automations list and clickable mock returned.'],
      ['2026-07-24T15:00:00+10:00', 'Sarah Whitfield', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-07-28T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Two iteration rounds agreed. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-07-29T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-08-12T17:30:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-08-14T13:00:00+10:00', 'Ramsay Hatfield', 'Scheduled 15-minute demo on preview. Feedback to the tracker.'],
      ['2026-08-17T09:00:00+10:00', 'Sarah Whitfield', 'Testing started. Moved from Preview to Testing.'],
      ['2026-08-21T16:00:00+10:00', 'Ramsay Hatfield', 'Iteration round one complete.'],
      ['2026-08-26T16:30:00+10:00', 'Ramsay Hatfield', 'Iteration round two complete.'],
      ['2026-08-28T10:30:00+10:00', 'Ramsay Hatfield', 'Promoted to production. Moved from Testing to Production.'],
      ['2026-09-01T09:00:00+10:00', 'Ramsay Hatfield', 'README written. Internal owner named: Sarah Whitfield.'],
      ['2026-09-09T13:15:00+10:00', 'Ramsay Hatfield', 'Hotfix promoted: approval threshold and GST-inclusive unit prices. See hotfix brief.'],
      ['2026-09-11T11:00:00+10:00', 'Ramsay Hatfield', 'Awaiting sign-off from Sarah Whitfield and Helen Marsh. Tests on the project record path pass.'],
    ]),
    attachments: [
      { id: 'att-b03-1', name: 'Purchase orders - process map v2.pdf', kind: 'pdf', size: 115804, uploadedBy: 'Sarah Whitfield', at: '2026-07-24T14:55:00+10:00', url: '/demo/purchase-orders-process-map-v2.pdf' },
      { id: 'att-b03-2', name: 'PO approval flow - current state.png', kind: 'image', size: 100629, uploadedBy: 'Sarah Whitfield', at: '2026-07-20T11:10:00+10:00', url: '/demo/po-approval-flow-current-state.png' },
      { id: 'att-b03-3', name: 'Brief - Purchase orders - raise and approve.docx', kind: 'docx', size: 1799, uploadedBy: 'Sarah Whitfield', at: '2026-07-24T14:58:00+10:00', url: '/demo/brief-purchase-orders-raise-and-approve.docx' },
    ],
  },
  {
    id: 'b04',
    title: 'Approval threshold ignores GST-inclusive unit prices',
    module: 'Purchase Orders',
    workstream: 'finance',
    department: 'Procurement',
    owner: 'Sarah Whitfield',
    priority: 'P1',
    workType: 'hotfix',
    days: 0.5,
    signOff: 'signed off',
    signOffBy: ['Sarah Whitfield'],
    stage: 'Production',
    outcome: 'A supplier quoted GST-inclusive unit prices. The PO routed to single approval when its ex GST value was over the threshold.',
    currentState: 'Reported 9 Sep 10:40. Fixed on production 13:15. Cause: line entry accepted inc GST prices with no flag.',
    lockDate: null,
    targetDate: null,
    previewUrl: '',
    readmeUrl: '#readme-purchase-orders',
    internalOwner: 'Sarah Whitfield',
    feedback: [],
    changeLog: log([
      ['2026-09-09T10:40:00+10:00', 'Sarah Whitfield', 'Hotfix logged. Bypasses the cycle.'],
      ['2026-09-09T11:05:00+10:00', 'Ramsay Hatfield', 'Reproduced on preview. Cause found.'],
      ['2026-09-09T13:15:00+10:00', 'Ramsay Hatfield', 'Fix promoted to production. Lines now carry an inc GST flag and are converted on entry.'],
      ['2026-09-09T14:02:00+10:00', 'Sarah Whitfield', 'Confirmed on production. Signed off.'],
    ]),
    attachments: [],
  },
  {
    id: 'b06',
    title: 'Progress claims - claim builder',
    module: 'Progress Claims',
    workstream: 'finance',
    department: 'Finance',
    owner: 'Kate Donnelly',
    priority: 'P1',
    workType: 'module',
    days: 9,
    signOff: 'not started',
    signOffBy: ['Kate Donnelly', 'Helen Marsh'],
    stage: 'Preview',
    outcome: 'Build a monthly claim from the project record, the schedule of rates and site percent complete. Export the client claim format. Track certified against claimed.',
    currentState: 'Claims assembled in Excel from four sources over two days each month. Version confusion on the client side.',
    lockDate: '2026-08-25',
    targetDate: '2026-10-02',
    previewUrl: 'https://platform-git-progress-claims.vercel.app',
    readmeUrl: '',
    internalOwner: 'Kate Donnelly',
    feedback: fb([['2026-09-11T10:30:00+10:00', 'Kate Donnelly', 'Retention should show as a running balance per project.', 'open']]),
    changeLog: log([
      ['2026-07-27T09:00:00+10:00', 'Kate Donnelly', 'Request raised. Entered Mapping.'],
      ['2026-07-28T10:00:00+10:00', 'Helen Marsh', 'Ranked P1.'],
      ['2026-08-21T15:00:00+10:00', 'Kate Donnelly', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-08-25T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-08-31T13:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-09-10T17:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-09-11T10:00:00+10:00', 'Ramsay Hatfield', 'Scheduled 15-minute demo on preview. One request filed as an integration.'],
    ]),
    attachments: [],
  },
  {
    id: 'b07',
    title: 'Variations log',
    module: 'Variations Log',
    workstream: 'finance',
    department: 'Finance',
    owner: 'Kate Donnelly',
    priority: 'P2',
    workType: 'module',
    days: 5,
    signOff: 'not started',
    signOffBy: ['Kate Donnelly'],
    stage: 'Build',
    outcome: 'Every variation raised, priced, submitted and approved in one list against the project. Nothing lost in email.',
    currentState: 'Variations tracked in the project manager inbox. Two were found unclaimed at project close.',
    lockDate: '2026-09-01',
    targetDate: '2026-09-30',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Kate Donnelly',
    feedback: [],
    changeLog: log([
      ['2026-08-10T09:00:00+10:00', 'Kate Donnelly', 'Request raised. Entered Mapping.'],
      ['2026-08-11T10:00:00+10:00', 'Helen Marsh', 'Ranked P2.'],
      ['2026-08-28T14:00:00+10:00', 'Kate Donnelly', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-09-01T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-09-07T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
    ]),
    attachments: [],
  },
  {
    id: 'b10',
    title: 'ERP sync - post approved POs',
    module: 'ERP Sync',
    workstream: 'finance',
    department: 'Finance',
    owner: 'Ben Carmichael',
    priority: 'P1',
    workType: 'integration',
    days: 4,
    signOff: 'not started',
    signOffBy: ['Ben Carmichael', 'Helen Marsh'],
    stage: 'Mapping',
    outcome: 'Approved POs post to the ERP as committed cost with no re-keying. Status flows back when the invoice is matched.',
    currentState: 'Accounts re-keys every approved PO. About four hours a week and the odd typo.',
    lockDate: null,
    targetDate: '2026-10-23',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Ben Carmichael',
    feedback: [],
    changeLog: log([
      ['2026-08-30T10:00:00+10:00', 'Sarah Whitfield', 'Request raised. Entered Mapping.'],
      ['2026-08-31T09:00:00+10:00', 'Helen Marsh', 'Ranked P1. Filed as integration. Batched for the next integration cycle, after the ERP connection.'],
    ]),
    attachments: [],
  },
  {
    id: 'b11',
    title: 'Project record feeds progress claims',
    module: 'Progress Claims',
    workstream: 'finance',
    department: 'Finance',
    owner: 'Kate Donnelly',
    priority: 'P2',
    workType: 'integration',
    days: 2,
    signOff: 'not started',
    signOffBy: ['Kate Donnelly'],
    stage: 'Mapping',
    outcome: 'Contract value, schedule of rates and retention terms flow from the project record into each claim. One source.',
    currentState: 'Raised during the claims preview. The claim builder currently asks for these values again.',
    lockDate: null,
    targetDate: '2026-10-23',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Kate Donnelly',
    feedback: [],
    changeLog: log([
      ['2026-09-11T10:20:00+10:00', 'Kate Donnelly', 'Request raised during the claims preview demo. Entered Mapping.'],
      ['2026-09-11T10:25:00+10:00', 'Helen Marsh', 'Ranked P2. Filed as integration. Not added to the claims build in flight.'],
    ]),
    attachments: [],
  },
  {
    id: 'b13',
    title: 'Purchase orders - receipting and three-way match',
    module: 'Purchase Orders',
    workstream: 'finance',
    department: 'Procurement',
    owner: 'Sarah Whitfield',
    priority: 'P2',
    workType: 'module',
    days: 6,
    signOff: 'not started',
    signOffBy: ['Sarah Whitfield', 'Helen Marsh'],
    stage: 'Mapping',
    outcome: 'Goods receipted against the PO. Invoice matched to PO and receipt before it is paid.',
    currentState: 'Receipting is a signature on a delivery docket. The match is done by accounts from memory.',
    lockDate: null,
    targetDate: '2026-11-20',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Sarah Whitfield',
    feedback: [],
    changeLog: log([
      ['2026-09-02T09:00:00+10:00', 'Sarah Whitfield', 'Request raised. Entered Mapping.'],
      ['2026-09-02T14:00:00+10:00', 'Helen Marsh', 'Ranked P2. Waits on the ERP sync.'],
    ]),
    attachments: [],
  },
  {
    id: 'fn08',
    title: 'Cost to complete on the project record',
    module: 'Project Record',
    workstream: 'finance',
    department: 'Finance',
    owner: 'Kate Donnelly',
    priority: 'P2',
    workType: 'integration',
    days: 4,
    signOff: 'not started',
    signOffBy: ['Kate Donnelly', 'Helen Marsh'],
    stage: 'Mapping',
    outcome: 'Committed, claimed and forecast cost on every project record, live from purchase orders and claims. The number the board asks for, without a spreadsheet.',
    currentState: 'Cost to complete is rebuilt in Excel for the monthly review.',
    lockDate: null,
    targetDate: '2026-11-06',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Kate Donnelly',
    feedback: [],
    changeLog: log([
      ['2026-09-05T09:00:00+10:00', 'Kate Donnelly', 'Request raised. Entered Mapping.'],
      ['2026-09-05T11:00:00+10:00', 'Helen Marsh', 'Ranked P2. Filed as integration. Needs POs and claims both live.'],
    ]),
    attachments: [],
  },

  // ---------- Site & HSEQ ----------
  {
    id: 'b05',
    title: 'Site diary - daily entries',
    module: 'Site Diary',
    workstream: 'site',
    department: 'Site',
    owner: 'Marcus Reid',
    priority: 'P2',
    workType: 'module',
    days: 6,
    signOff: 'awaiting',
    signOffBy: ['Marcus Reid'],
    stage: 'Testing',
    outcome: 'Site managers log weather, crew, plant, delays and visitors from a phone. The diary is the record when a delay claim comes.',
    currentState: 'Paper diary in the site office, photographed to Teams on Fridays. Some weeks missing.',
    lockDate: '2026-08-20',
    targetDate: '2026-09-25',
    previewUrl: 'https://platform-git-site-diary.vercel.app',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: fb([
      ['2026-09-08T15:10:00+10:00', 'Marcus Reid', 'Crew count needs subcontractor crews split out from our own.', 'addressed'],
      ['2026-09-10T07:50:00+10:00', 'Marcus Reid', 'Weather should default from the nearest BoM station, not a free text field.', 'open'],
    ]),
    changeLog: log([
      ['2026-08-03T09:00:00+10:00', 'Marcus Reid', 'Request raised. Entered Mapping.'],
      ['2026-08-04T10:30:00+10:00', 'Helen Marsh', 'Ranked P2.'],
      ['2026-08-18T14:00:00+10:00', 'Marcus Reid', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-08-20T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set.'],
      ['2026-08-31T08:00:00+10:00', 'Ramsay Hatfield', 'Build started. Moved from Locked to Build.'],
      ['2026-09-05T16:00:00+10:00', 'Ramsay Hatfield', 'Preview URL added. Moved from Build to Preview.'],
      ['2026-09-08T09:00:00+10:00', 'Marcus Reid', 'Testing started on site. Moved from Preview to Testing.'],
    ]),
    attachments: [],
  },
  {
    id: 'b08',
    title: 'Subcontractor onboarding',
    module: 'Subcontractor Onboarding',
    workstream: 'site',
    department: 'HSEQ',
    owner: 'Marcus Reid',
    priority: 'P2',
    workType: 'module',
    days: 7,
    signOff: 'not started',
    signOffBy: ['Marcus Reid', 'Helen Marsh'],
    stage: 'Locked',
    outcome: 'A subcontractor submits insurances, licences and inductions once. Expiry dates tracked. No one starts on site without a green tick.',
    currentState: 'Compliance folder on SharePoint, checked by hand before mobilisation. Expired insurance found on site twice this year.',
    lockDate: '2026-09-10',
    targetDate: '2026-10-16',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: [],
    changeLog: log([
      ['2026-08-17T09:00:00+10:00', 'Marcus Reid', 'Request raised. Entered Mapping.'],
      ['2026-08-18T10:00:00+10:00', 'Helen Marsh', 'Ranked P2.'],
      ['2026-09-08T15:00:00+10:00', 'Marcus Reid', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
      ['2026-09-10T09:00:00+10:00', 'Helen Marsh', 'Brief approved. Moved from Briefed in to Locked. Lock date set. Build starts after the variations log.'],
    ]),
    attachments: [],
  },
  {
    id: 's03',
    title: 'Site inductions and competencies',
    module: 'HSEQ',
    workstream: 'site',
    department: 'HSEQ',
    owner: 'Marcus Reid',
    priority: 'P2',
    workType: 'module',
    days: 5,
    signOff: 'not started',
    signOffBy: ['Marcus Reid'],
    stage: 'Briefed in',
    outcome: 'Every person on site has a current induction and the tickets the work needs, checked at the gate from a phone.',
    currentState: 'Induction register is a spreadsheet per site. Tickets are photocopies in a folder.',
    lockDate: null,
    targetDate: '2026-11-06',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: [],
    changeLog: log([
      ['2026-09-04T09:00:00+10:00', 'Marcus Reid', 'Request raised. Entered Mapping.'],
      ['2026-09-04T11:00:00+10:00', 'Helen Marsh', 'Ranked P2. Pairs with subcontractor onboarding.'],
      ['2026-09-12T15:00:00+10:00', 'Marcus Reid', 'Brief submitted. Moved from Mapping to Briefed in.'],
    ]),
    attachments: [],
  },
  {
    id: 's04',
    title: 'Incident and hazard reporting',
    module: 'HSEQ',
    workstream: 'site',
    department: 'HSEQ',
    owner: 'Marcus Reid',
    priority: 'P2',
    workType: 'module',
    days: 5,
    signOff: 'not started',
    signOffBy: ['Marcus Reid', 'Helen Marsh'],
    stage: 'Mapping',
    outcome: 'Incidents and hazards reported from the field in minutes, with photos, and routed to the right person. The evidence the safety system needs, as it happens.',
    currentState: 'A paper form and a phone call. Reports reach the office days later.',
    lockDate: null,
    targetDate: '2026-11-27',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: [],
    changeLog: log([
      ['2026-09-10T09:00:00+10:00', 'Marcus Reid', 'Request raised. Entered Mapping.'],
      ['2026-09-10T11:00:00+10:00', 'Helen Marsh', 'Ranked P2.'],
    ]),
    attachments: [],
  },
  {
    id: 'b12',
    title: 'Site diary - photo capture',
    module: 'Site Diary',
    workstream: 'site',
    department: 'Site',
    owner: 'Marcus Reid',
    priority: 'P3',
    workType: 'module',
    days: 3,
    signOff: 'not started',
    signOffBy: ['Marcus Reid'],
    stage: 'Mapping',
    outcome: 'Photos taken on site attach to the day entry with location and time.',
    currentState: 'Photos sit on personal phones.',
    lockDate: null,
    targetDate: '2026-11-13',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Marcus Reid',
    feedback: [],
    changeLog: log([
      ['2026-09-08T15:30:00+10:00', 'Marcus Reid', 'Request raised during site diary testing. Entered Mapping.'],
      ['2026-09-09T09:00:00+10:00', 'Helen Marsh', 'Ranked P3. After the diary is done.'],
    ]),
    attachments: [],
  },

  // ---------- Reporting ----------
  {
    id: 'b09',
    title: 'Board reporting - monthly pack',
    module: 'Board Reporting',
    workstream: 'reporting',
    department: 'Finance',
    owner: 'Helen Marsh',
    priority: 'P2',
    workType: 'module',
    days: 8,
    signOff: 'not started',
    signOffBy: ['Helen Marsh'],
    stage: 'Briefed in',
    outcome: 'Monthly pack built from the platform: work in hand, claims, cash, safety. Every number traceable to its source.',
    currentState: 'Pack assembled in PowerPoint over three days from ERP exports and emails.',
    lockDate: null,
    targetDate: '2026-11-06',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Helen Marsh',
    feedback: [],
    changeLog: log([
      ['2026-09-03T09:00:00+10:00', 'Helen Marsh', 'Request raised. Entered Mapping.'],
      ['2026-09-03T09:05:00+10:00', 'Helen Marsh', 'Ranked P2. Depends on claims and the project record.'],
      ['2026-09-11T16:00:00+10:00', 'Helen Marsh', 'Brief submitted with process map attached. Moved from Mapping to Briefed in.'],
    ]),
    attachments: [],
  },
  {
    id: 'r02',
    title: 'Project dashboards - stage, cost, risk',
    module: 'Dashboards',
    workstream: 'reporting',
    department: 'Finance',
    owner: 'Helen Marsh',
    priority: 'P2',
    workType: 'module',
    days: 6,
    signOff: 'not started',
    signOffBy: ['Helen Marsh', 'Tom Aldridge'],
    stage: 'Mapping',
    outcome: 'One screen per project and one across all of them: stage, gate status, committed and claimed cost, open hold points. Live.',
    currentState: 'The Monday meeting slide deck.',
    lockDate: null,
    targetDate: '2026-11-20',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Helen Marsh',
    feedback: [],
    changeLog: log([
      ['2026-09-08T09:00:00+10:00', 'Helen Marsh', 'Request raised. Entered Mapping.'],
      ['2026-09-08T09:10:00+10:00', 'Helen Marsh', 'Ranked P2. After cost to complete lands on the record.'],
    ]),
    attachments: [],
  },
  {
    id: 'r03',
    title: 'Ask the platform a question',
    module: 'Dashboards',
    workstream: 'reporting',
    department: 'Finance',
    owner: 'Helen Marsh',
    priority: 'P3',
    workType: 'module',
    days: 8,
    signOff: 'not started',
    signOffBy: ['Helen Marsh'],
    stage: 'Mapping',
    outcome: 'A plain-English question box over the platform data for the people who run the business. Read-only, every answer shows the numbers it used.',
    currentState: 'Questions go to whoever owns the spreadsheet.',
    lockDate: null,
    targetDate: '2026-12-11',
    previewUrl: '',
    readmeUrl: '',
    internalOwner: 'Helen Marsh',
    feedback: [],
    changeLog: log([
      ['2026-09-11T09:00:00+10:00', 'Helen Marsh', 'Request raised. Entered Mapping.'],
      ['2026-09-11T09:05:00+10:00', 'Helen Marsh', 'Ranked P3. Once the data is there to ask about.'],
    ]),
    attachments: [],
  },
]

// ---------- Purchase orders ----------

type AuditSeed = [at: string, who: string, action: string]
const audit = (entries: AuditSeed[]) =>
  entries.map(([at, who, action], i) => ({ id: `a${i}-${at}`, at, who, action }))

const line = (id: string, description: string, qty: number, unitPrice: number) => ({
  id,
  description,
  qty,
  unitPrice,
})

const PM = 'Tom Aldridge'
const HOF = 'Helen Marsh'

const approved = (role: 'Project manager' | 'Head of Finance', approver: string, at: string, note = '') => ({
  role,
  approver,
  decision: 'approved' as const,
  note,
  at,
})
const pending = (role: 'Project manager' | 'Head of Finance', approver: string) => ({
  role,
  approver,
  decision: 'pending' as const,
  note: '',
  at: null,
})
const noSync = () => ({ synced: false, at: null, reference: null, log: [] })
const synced = (at: string, reference: string) => ({
  synced: true,
  at,
  reference,
  log: [
    { at, text: `Posted to ERP as ${reference}. Committed cost recorded against the project.` },
  ],
})

export const PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po01',
    number: 'PO-2026-0401',
    supplierId: 's1',
    projectId: 'p1',
    lines: [line('l1', '33kV switchgear panel, incomer', 1, 52500), line('l2', '33kV switchgear panel, feeder', 2, 46500)],
    status: 'Closed',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-07-30T09:10:00+10:00',
    updatedAt: '2026-08-26T11:00:00+10:00',
    approvals: [approved('Project manager', PM, '2026-07-30T13:20:00+10:00'), approved('Head of Finance', HOF, '2026-07-31T08:45:00+10:00', 'Within the switchgear budget line.')],
    erp: synced('2026-07-31T09:00:00+10:00', 'ERP-88213'),
    attachments: ['SSW-quote-4471.pdf'],
    audit: audit([
      ['2026-07-30T09:10:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-07-30T09:12:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-07-30T13:20:00+10:00', PM, 'Approved as project manager.'],
      ['2026-07-31T08:45:00+10:00', HOF, 'Approved as Head of Finance. Note: Within the switchgear budget line.'],
      ['2026-07-31T09:00:00+10:00', 'System', 'Sent to ERP as ERP-88213.'],
      ['2026-08-26T11:00:00+10:00', 'Sarah Whitfield', 'Closed. Goods received and invoice matched.'],
    ]),
  },
  {
    id: 'po02',
    number: 'PO-2026-0402',
    supplierId: 's3',
    projectId: 'p1',
    lines: [line('l1', '240mm2 Al XLPE 33kV cable, per metre', 1200, 38.4)],
    status: 'Sent to ERP',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-08-04T10:30:00+10:00',
    updatedAt: '2026-08-05T08:30:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-04T15:10:00+10:00'), approved('Head of Finance', HOF, '2026-08-05T08:20:00+10:00')],
    erp: synced('2026-08-05T08:30:00+10:00', 'ERP-88240'),
    attachments: ['HEW-quote-1188.pdf'],
    audit: audit([
      ['2026-08-04T10:30:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-08-04T10:31:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-08-04T15:10:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-05T08:20:00+10:00', HOF, 'Approved as Head of Finance.'],
      ['2026-08-05T08:30:00+10:00', 'System', 'Sent to ERP as ERP-88240.'],
    ]),
  },
  {
    id: 'po03',
    number: 'PO-2026-0403',
    supplierId: 's2',
    projectId: 'p1',
    lines: [line('l1', '80t crane with operator, per day', 3, 4200)],
    status: 'Closed',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-08-06T07:45:00+10:00',
    updatedAt: '2026-08-20T16:00:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-06T07:50:00+10:00')],
    erp: synced('2026-08-06T08:00:00+10:00', 'ERP-88251'),
    attachments: [],
    audit: audit([
      ['2026-08-06T07:45:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-08-06T07:46:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager.'],
      ['2026-08-06T07:50:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-06T08:00:00+10:00', 'System', 'Sent to ERP as ERP-88251.'],
      ['2026-08-20T16:00:00+10:00', 'Sarah Whitfield', 'Closed. Invoice matched.'],
    ]),
  },
  {
    id: 'po04',
    number: 'PO-2026-0404',
    supplierId: 's4',
    projectId: 'p2',
    lines: [line('l1', 'Cable trench excavation and backfill, per metre', 850, 62)],
    status: 'Approved',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-09-01T08:15:00+10:00',
    updatedAt: '2026-09-02T09:40:00+10:00',
    approvals: [approved('Project manager', PM, '2026-09-01T08:20:00+10:00'), approved('Head of Finance', HOF, '2026-09-02T09:40:00+10:00', 'Approved. Confirm the rate matches the subcontract schedule.')],
    erp: noSync(),
    attachments: ['BCC-schedule-of-rates.pdf'],
    audit: audit([
      ['2026-09-01T08:15:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-09-01T08:16:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-09-01T08:20:00+10:00', PM, 'Approved as project manager.'],
      ['2026-09-02T09:40:00+10:00', HOF, 'Approved as Head of Finance. Note: Approved. Confirm the rate matches the subcontract schedule.'],
    ]),
  },
  {
    id: 'po05',
    number: 'PO-2026-0405',
    supplierId: 's3',
    projectId: 'p2',
    lines: [line('l1', 'Cable lugs 240mm2, box of 50', 4, 312), line('l2', 'Heat shrink kit 33kV', 6, 148.5), line('l3', 'Cable ties, UV rated, bag of 100', 10, 26.9)],
    status: 'Sent to ERP',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-08-18T11:00:00+10:00',
    updatedAt: '2026-08-18T14:30:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-18T14:25:00+10:00')],
    erp: synced('2026-08-18T14:30:00+10:00', 'ERP-88302'),
    attachments: [],
    audit: audit([
      ['2026-08-18T11:00:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-08-18T11:02:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager.'],
      ['2026-08-18T14:25:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-18T14:30:00+10:00', 'System', 'Sent to ERP as ERP-88302.'],
    ]),
  },
  {
    id: 'po06',
    number: 'PO-2026-0406',
    supplierId: 's5',
    projectId: 'p3',
    lines: [line('l1', 'Power transformer factory acceptance test attendance', 1, 18750)],
    status: 'Approved',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-09-03T09:00:00+10:00',
    updatedAt: '2026-09-03T09:05:00+10:00',
    approvals: [approved('Project manager', PM, '2026-09-03T09:05:00+10:00')],
    erp: noSync(),
    attachments: ['NTS-proposal-0921.pdf'],
    audit: audit([
      ['2026-09-03T09:00:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-09-03T09:01:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager.'],
      ['2026-09-03T09:05:00+10:00', PM, 'Approved as project manager.'],
    ]),
  },
  {
    id: 'po07',
    number: 'PO-2026-0407',
    supplierId: 's1',
    projectId: 'p3',
    lines: [line('l1', '132kV current transformer, set of three', 2, 29400)],
    status: 'Submitted',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-09-09T10:00:00+10:00',
    updatedAt: '2026-09-09T16:20:00+10:00',
    approvals: [approved('Project manager', PM, '2026-09-09T16:20:00+10:00'), pending('Head of Finance', HOF)],
    erp: noSync(),
    attachments: ['SSW-quote-4530.pdf'],
    audit: audit([
      ['2026-09-09T10:00:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-09-09T10:03:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-09-09T16:20:00+10:00', PM, 'Approved as project manager.'],
    ]),
  },
  {
    id: 'po08',
    number: 'PO-2026-0408',
    supplierId: 's2',
    projectId: 'p3',
    lines: [line('l1', '80t crane with operator, per day', 2, 4200)],
    status: 'Submitted',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-09-10T13:30:00+10:00',
    updatedAt: '2026-09-10T13:31:00+10:00',
    approvals: [pending('Project manager', PM)],
    erp: noSync(),
    attachments: [],
    audit: audit([
      ['2026-09-10T13:30:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-09-10T13:31:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager.'],
    ]),
  },
  {
    id: 'po09',
    number: 'PO-2026-0409',
    supplierId: 's4',
    projectId: 'p4',
    lines: [line('l1', 'Access track construction, per metre', 2400, 41)],
    status: 'Rejected',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-08-27T08:00:00+10:00',
    updatedAt: '2026-08-27T15:45:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-27T08:05:00+10:00'), { role: 'Head of Finance', approver: HOF, decision: 'rejected', note: 'Hold until the landholder access agreement is signed.', at: '2026-08-27T15:45:00+10:00' }],
    erp: noSync(),
    attachments: [],
    audit: audit([
      ['2026-08-27T08:00:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-08-27T08:01:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-08-27T08:05:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-27T15:45:00+10:00', HOF, 'Rejected as Head of Finance. Note: Hold until the landholder access agreement is signed.'],
    ]),
  },
  {
    id: 'po10',
    number: 'PO-2026-0410',
    supplierId: 's3',
    projectId: 'p4',
    lines: [line('l1', 'Bare copper earthing conductor 120mm2, per metre', 600, 22.5)],
    status: 'Draft',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-09-11T09:20:00+10:00',
    updatedAt: '2026-09-11T09:20:00+10:00',
    approvals: [],
    erp: noSync(),
    attachments: [],
    audit: audit([['2026-09-11T09:20:00+10:00', 'Sarah Whitfield', 'Raised. Saved as draft.']]),
  },
  {
    id: 'po11',
    number: 'PO-2026-0411',
    supplierId: 's5',
    projectId: 'p1',
    lines: [line('l1', 'Transformer oil sample and dissolved gas analysis', 12, 380)],
    status: 'Closed',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-08-11T10:00:00+10:00',
    updatedAt: '2026-09-02T10:00:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-11T10:04:00+10:00')],
    erp: synced('2026-08-11T10:10:00+10:00', 'ERP-88270'),
    attachments: [],
    audit: audit([
      ['2026-08-11T10:00:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-08-11T10:01:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager.'],
      ['2026-08-11T10:04:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-11T10:10:00+10:00', 'System', 'Sent to ERP as ERP-88270.'],
      ['2026-09-02T10:00:00+10:00', 'Sarah Whitfield', 'Closed. Invoice matched.'],
    ]),
  },
  {
    id: 'po12',
    number: 'PO-2026-0412',
    supplierId: 's1',
    projectId: 'p2',
    lines: [line('l1', '33kV ring main unit, three way', 2, 21900)],
    status: 'Closed',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-08-13T14:00:00+10:00',
    updatedAt: '2026-09-08T09:00:00+10:00',
    approvals: [approved('Project manager', PM, '2026-08-13T16:30:00+10:00'), approved('Head of Finance', HOF, '2026-08-14T08:10:00+10:00')],
    erp: synced('2026-08-14T08:15:00+10:00', 'ERP-88288'),
    attachments: ['SSW-quote-4498.pdf'],
    audit: audit([
      ['2026-08-13T14:00:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-08-13T14:02:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager, then Head of Finance.'],
      ['2026-08-13T16:30:00+10:00', PM, 'Approved as project manager.'],
      ['2026-08-14T08:10:00+10:00', HOF, 'Approved as Head of Finance.'],
      ['2026-08-14T08:15:00+10:00', 'System', 'Sent to ERP as ERP-88288.'],
      ['2026-09-08T09:00:00+10:00', 'Sarah Whitfield', 'Closed. Goods received and invoice matched.'],
    ]),
  },
  {
    id: 'po13',
    number: 'PO-2026-0413',
    supplierId: 's2',
    projectId: 'p4',
    lines: [line('l1', '100t crane mobilisation and demobilisation', 1, 6800), line('l2', '100t crane with operator, per day', 2, 5900)],
    status: 'Sent to ERP',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-09-04T07:30:00+10:00',
    updatedAt: '2026-09-04T07:45:00+10:00',
    approvals: [approved('Project manager', PM, '2026-09-04T07:40:00+10:00')],
    erp: synced('2026-09-04T07:45:00+10:00', 'ERP-88341'),
    attachments: [],
    audit: audit([
      ['2026-09-04T07:30:00+10:00', 'Tom Aldridge', 'Raised.'],
      ['2026-09-04T07:31:00+10:00', 'Tom Aldridge', 'Submitted for approval. Routed to project manager.'],
      ['2026-09-04T07:40:00+10:00', PM, 'Approved as project manager.'],
      ['2026-09-04T07:45:00+10:00', 'System', 'Sent to ERP as ERP-88341.'],
    ]),
  },
  {
    id: 'po14',
    number: 'PO-2026-0414',
    supplierId: 's4',
    projectId: 'p3',
    lines: [line('l1', 'Concrete transformer plinth, supply and pour', 4, 5400)],
    status: 'Submitted',
    raisedBy: 'Sarah Whitfield',
    raisedAt: '2026-09-11T15:00:00+10:00',
    updatedAt: '2026-09-11T15:02:00+10:00',
    approvals: [pending('Project manager', PM)],
    erp: noSync(),
    attachments: ['BCC-quote-2210.pdf'],
    audit: audit([
      ['2026-09-11T15:00:00+10:00', 'Sarah Whitfield', 'Raised.'],
      ['2026-09-11T15:02:00+10:00', 'Sarah Whitfield', 'Submitted for approval. Routed to project manager.'],
    ]),
  },
  {
    id: 'po15',
    number: 'PO-2026-0415',
    supplierId: 's3',
    projectId: 'p2',
    lines: [line('l1', '33kV outdoor termination kit', 24, 640)],
    status: 'Draft',
    raisedBy: 'Tom Aldridge',
    raisedAt: '2026-09-12T08:10:00+10:00',
    updatedAt: '2026-09-12T08:10:00+10:00',
    approvals: [],
    erp: noSync(),
    attachments: [],
    audit: audit([['2026-09-12T08:10:00+10:00', 'Tom Aldridge', 'Raised. Saved as draft.']]),
  },
]

export const NEXT_PO_SEQUENCE = 416

// Module names offered when a new request is raised.
export const MODULES = ['Identity', 'Tracker', 'Project Record', 'Audit', 'Engineering', 'Construction', 'Commissioning', 'Purchase Orders', 'Progress Claims', 'Variations Log', 'ERP Sync', 'Site Diary', 'Subcontractor Onboarding', 'HSEQ', 'Board Reporting', 'Dashboards']
